# Generated by Django 2.2 on 2020-12-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('production', models.CharField(max_length=50)),
                ('prod_type', models.CharField(max_length=30)),
                ('genres', models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('sci_fi', 'Sci-Fi'), ('anime', 'Anime')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
