# Generated by Django 2.2 on 2020-12-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk_collection_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disks',
            name='genres',
        ),
    ]
