# Generated by Django 2.2 on 2020-12-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk_collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disks',
            name='released_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='disks',
            name='genres',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
