# Generated by Django 2.2 on 2020-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk_collection_app', '0002_auto_20201220_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disks',
            name='released_date',
            field=models.DateField(null=True),
        ),
    ]
