# Generated by Django 2.2 on 2020-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk_collection_app', '0002_remove_disks_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='disks',
            name='genres',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
