# Generated by Django 2.2 on 2020-12-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk_collection_app', '0003_disks_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='disks',
            name='released_date',
            field=models.DateField(default=None),
        ),
    ]
